blogs/urls.py
from django.urls import path
from .views import ListView, BlogListView,BlogDetailView,BlogCreateView,BlogDeleteView,AddReviewView,ReviewDeleteView,ReviewUpdateView

app_name = 'blogs'
urlpatterns = [
    path('blogs/',BlogListView.as_view(),name='blog_list'),
    path('deatail/<int:pk>',BlogDetailView.as_view(),name='blog_detail'),
    path('create/',BlogCreateView.as_view(),name='blog_create'),
    path('delete/<int:pk>',BlogDeleteView.as_view(),name='blog_delete'),
    path('add_review/<int:pk>', AddReviewView.as_view(), name='add_review'),  
    path('review_delete/<int:pk>', ReviewDeleteView.as_view(), name='review_delete'),
    path('review_update/<int:pk>', ReviewUpdateView.as_view(), name='review_update'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blogs/', include('blogs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, Analaze

app_name = 'home'
urlpatterns = [
    path('',home_page, name='home_page'),
    path('analaze/', Analaze.as_view(), name='analaze'),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView,ProfileView,UpdateProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', UpdateProfileView.as_view(), name='edit_profile'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def home_page(request):
    return render(request, 'home.html')

class Analaze(LoginRequiredMixin,View):
    def get(self, request):
        if request.user.is_authenticated():
            return render(request, 'users:logout')
        else:
            return render(request, 'users:login')
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    <hr>
    {% endif %}
    
    <a href="{% url 'home:home_page' %}">Home</a> /
    <a href="{% url 'blogs:blog_list' %}">Blogs</a> /
    <a href="{% url 'users:register' %}">Register</a> /
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:profile' %}">Profile</a>/    
        <a href="{% url 'users:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}    
    
    {% block content %} {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
<title>{% block title %} Home page{% endblock %}</title>
{% block content %}

    <h1>Home page</h1>
    <p>Welcome to the home page</p>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
<title>{% block title %} Profile{% endblock %}</title>
{% block content %}
    <h1>Profile</h1>
    <div >
        <img src="{{user.image.url}}" alt="Your image" height="100px">
        <h2>Username: {{user.username}}</h2>
        <h3>Email: {{ user.email }}</h3>
        <h3>First Name: {{ user.first_name }}</h3>
        <h3>Last Name: {{ user.last_name }}</h3>
        <button>
            <a href="{% url 'users:edit_profile' %}">Edit Profile</a>
        </button>
    </div>
                                    

{% endblock %}